[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Manolo <manolo@manolo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^1.13.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"